# *******************************
# *** Autor: Reymon Dev       ***
# *** Datum: 08. Juli. 2026   ***
# *** Aktua: 08. Juli. 2026   ***
# *** Lizenz: MIT             ***
# *******************************

source_files_twsclient_ticker = files(
	'tickByTickBidAsk.cpp',
	'tickByTickMidPoint.cpp',
	'tickDataOperation.cpp',
	'tickEFP.cpp',
	'tickGeneric.cpp',
	'tickOptionComputation.cpp',
	'tickOptionComputationOperation.cpp',
	'tickReqParams.cpp',
	'tickSize.cpp',
	'tickSnapshotEnd.cpp',
	'tickString.cpp'
)

# **************************************
# *** Constrol Addition Source Files ***
# **************************************

source_files_twsclient += source_files_twsclient_ticker