# *****************************
# *** Autor: Reymon Dev     ***
# *** Datum: 26. Juli. 2026 ***
# *** Aktua: 27. Juli. 2026 ***
# *** Lizenz: MIT           ***
# *****************************

SOURCE_FILES_TWSCLIENT_HISTORICAL = files(
	'histogramData.cpp',
	'historicalData.cpp',
	'historicalDataEnd.cpp',
	'historicalDataRequests.cpp',
	'historicalDataUpdate.cpp',
	'historicalNews.cpp',
	'historicalNewsEnd.cpp',
	'historicalSchedule.cpp',
	'historicalTicks.cpp',
	'historicalTicksBidAsk.cpp',
	'historicalTicksLast.cpp',
	'reqHeadTimestamp.cpp',
	'reqHistogramData.cpp',
	'reqHistoricalNews.cpp',
	'reqHistoricalTicks.cpp',
	'reqTickByTickData.cpp'
)