# *******************************
# *** Autor: Reymon Dev       ***
# *** Datum: 08. Juli. 2026   ***
# *** Aktua: 08. Juli. 2026   ***
# *** Lizenz: AGPL-3-or-later ***
# *******************************

source_files_twsclient_historical = files(
	'histogramData.cpp',
	'historicalData.cpp',
	'historicalDataEnd.cpp',
	'historicalDataRequests.cpp',
	'historicalDataUpdate.cpp',
	'historicalNews.cpp',
	'historicalNewsEnd.cpp',
	'historicalSchedule.cpp',
	'historicalTicks.cpp',
	'historicalTicksBidAsk.cpp',
	'historicalTicksLast.cpp',
	'reqHeadTimestamp.cpp',
	'reqHistogramData.cpp',
	'reqHistoricalNews.cpp',
	'reqHistoricalTicks.cpp',
	'reqTickByTickData.cpp'
)

# **************************************
# *** Constrol Addition Source Files ***
# **************************************

source_files_twsclient += source_files_twsclient_historical