# *******************************
# *** Autor: Reymon Dev       ***
# *** Datum: 08. Juli. 2026   ***
# *** Aktua: 08. Juli. 2026   ***
# *** Lizenz: AGPL-3-or-later ***
# *******************************

source_files_twsclient_client = files(
	'constructor.cpp',
	'destructor.cpp',
	'start.cpp',
	'userInfo.cpp',
	'verifyMessageAPI.cpp'
)

# **************************************
# *** Constrol Addition Source Files ***
# **************************************

source_files_twsclient += source_files_twsclient_client