# *****************************
# *** Autor: Reymon Dev     ***
# *** Datum: 26. Juli. 2026 ***
# *** Aktua: 27. Juli. 2026 ***
# *** Lizenz: MIT           ***
# *****************************

SOURCE_FILES_TWSCLIENT_PNL = files(
	'commissionAndFeesReport.cpp',
	'pnl.cpp',
	'pnlOperation.cpp',
	'pnlSingle.cpp',
	'pnlSingleOperation.cpp'
)