# *****************************
# *** Autor: Reymon Dev     ***
# *** Datum: 26. Juli. 2026 ***
# *** Aktua: 27. Juli. 2026 ***
# *** Lizenz: MIT           ***
# *****************************

SOURCE_FILES_TWSCLIENT_OTHER = files(
	'deltaNeutralValidation.cpp',
	'displayGroupList.cpp',
	'displayGroupUpdated.cpp',
	'execDetails.cpp',
	'execDetailsEnd.cpp',
	'familyCodes.cpp',
	'receiveFA.cpp',
	'replaceFAEnd.cpp',
	'securityDefinitionOptionalParameter.cpp',
	'securityDefinitionOptionalParameterEnd.cpp',
	'smartComponents.cpp',
	'softDollarTiers.cpp',
	'verifyAndAuthCompleted.cpp',
	'verifyAndAuthMessageAPI.cpp',
	'verifyCompleted.cpp'
)