# *******************************
# *** Autor: Reymon Dev       ***
# *** Datum: 08. Juli. 2026   ***
# *** Aktua: 08. Juli. 2026   ***
# *** Lizenz: MIT             ***
# *******************************

source_files_twsclient_account = files(
	'accountDownloadEnd.cpp',
	'accountSummary.cpp',
	'accountSummaryEnd.cpp',
	'accountUpdateMulti.cpp',
	'accountUpdateMultiEnd.cpp',
	'managedAccounts.cpp',
	'updateAccountTime.cpp',
	'updateAccountValue.cpp'
)

# **************************************
# *** Constrol Addition Source Files ***
# **************************************

source_files_twsclient += source_files_twsclient_account