# *****************************
# *** Autor: Reymon Dev     ***
# *** Datum: 26. Juli. 2026 ***
# *** Aktua: 27. Juli. 2026 ***
# *** Lizenz: MIT           ***
# *****************************

SOURCE_FILES_TWSCLIENT_ACCOUNT = files(
	'accountDownloadEnd.cpp',
	'accountSummary.cpp',
	'accountSummaryEnd.cpp',
	'accountUpdateMulti.cpp',
	'accountUpdateMultiEnd.cpp',
	'managedAccounts.cpp',
	'updateAccountTime.cpp',
	'updateAccountValue.cpp'
)