# *****************************
# *** Autor: Reymon Dev     ***
# *** Datum: 26. Juli. 2026 ***
# *** Aktua: 27. Juli. 2026 ***
# *** Lizenz: MIT           ***
# *****************************

SOURCE_FILES_TWSCLIENT_MARKET = files(
	'delayedTickDataOperation.cpp',
	'marketDataType.cpp',
	'marketDepthOperations.cpp',
	'marketRule.cpp',
	'mktDepthExchanges.cpp',
	'realTimeBars.cpp',
	'realtimeBar.cpp',
	'reqMktDepthExchanges.cpp',
	'reqSmartComponents.cpp',
	'rerouteMktDataReq.cpp',
	'rerouteMktDepthReq.cpp',
	'symbolSamples.cpp',
	'updateMktDepth.cpp',
	'updateMktDepthL2.cpp'
)