# *******************************
# *** Autor: Reymon Dev       ***
# *** Datum: 08. Juli. 2026   ***
# *** Aktua: 08. Juli. 2026   ***
# *** Lizenz: AGPL-3-or-later ***
# *******************************

source_files_twsclient_market = files(
	'delayedTickDataOperation.cpp',
	'marketDataType.cpp',
	'marketDepthOperations.cpp',
	'marketRule.cpp',
	'mktDepthExchanges.cpp',
	'realTimeBars.cpp',
	'realtimeBar.cpp',
	'reqMktDepthExchanges.cpp',
	'reqSmartComponents.cpp',
	'rerouteMktDataReq.cpp',
	'rerouteMktDepthReq.cpp',
	'symbolSamples.cpp',
	'updateMktDepth.cpp',
	'updateMktDepthL2.cpp'
)

# **************************************
# *** Constrol Addition Source Files ***
# **************************************

source_files_twsclient += source_files_twsclient_market