# *******************************
# *** Autor: Reymon Dev       ***
# *** Datum: 08. Juli. 2026   ***
# *** Aktua: 24. Juli. 2026   ***
# *** Lizenz: MIT             ***
# *******************************

source_files_twsclient_time= files(
	'currentTime.cpp',
	'currentTimeInMillis.cpp',
	'headTimestamp.cpp',
	'reqCurrentTime.cpp',
	'tickByTickAllLast.cpp',
	'wshCalendarOperations.cpp',
	'wshEventData.cpp',
	'wshMetaData.cpp'
)

# **************************************
# *** Constrol Addition Source Files ***
# **************************************

source_files_twsclient += source_files_twsclient_time