# *****************************
# *** Autor: Reymon Dev     ***
# *** Datum: 26. Juli. 2026 ***
# *** Aktua: 27. Juli. 2026 ***
# *** Lizenz: MIT           ***
# *****************************

SOURCE_FILES_TWSCLIENT_TIME= files(
	'currentTime.cpp',
	'currentTimeInMillis.cpp',
	'headTimestamp.cpp',
	'reqCurrentTime.cpp',
	'tickByTickAllLast.cpp',
	'wshCalendarOperations.cpp',
	'wshEventData.cpp',
	'wshMetaData.cpp'
)