# *******************************
# *** Autor: Reymon Dev       ***
# *** Datum: 08. Juli. 2026   ***
# *** Aktua: 08. Juli. 2026   ***
# *** Lizenz: MIT             ***
# *******************************

source_files_twsclient_advisor = files(
	'financialAdvisorOperations.cpp'
)

# **************************************
# *** Constrol Addition Source Files ***
# **************************************

source_files_twsclient += source_files_twsclient_advisor