# *******************************
# *** Autor: Reymon Dev       ***
# *** Datum: 08. Juli. 2026   ***
# *** Aktua: 08. Juli. 2026   ***
# *** Lizenz: MIT             ***
# *******************************

source_files_twsclient_portfolio = files(
	'position.cpp',
	'positionEnd.cpp',
	'positionMulti.cpp',
	'positionMultiEnd.cpp',
	'updatePortfolio.cpp'
)

# **************************************
# *** Constrol Addition Source Files ***
# **************************************

source_files_twsclient += source_files_twsclient_portfolio