# *******************************
# *** Autor: Reymon Dev       ***
# *** Datum: 08. Juli. 2026   ***
# *** Aktua: 08. Juli. 2026   ***
# *** Lizenz: MIT             ***
# *******************************

source_files_twsclient_protobuf = files(
	'accountDataEndProtoBuf.cpp',
	'accountSummaryEndProtoBuf.cpp',
	'accountSummaryProtoBuf.cpp',
	'accountUpdateMultiEndProtoBuf.cpp',
	'accountUpdateMultiProtoBuf.cpp',
	'bondContractDataProtoBuf.cpp',
	'commissionAndFeesReportProtoBuf.cpp',
	'completedOrderProtoBuf.cpp',
	'completedOrdersEndProtoBuf.cpp',
	'configResponseProtoBuf.cpp',
	'contractDataEndProtoBuf.cpp',
	'contractDataProtoBuf.cpp',
	'currentTimeInMillisProtoBuf.cpp',
	'currentTimeProtoBuf.cpp',
	'displayGroupListProtoBuf.cpp',
	'displayGroupUpdatedProtoBuf.cpp',
	'errorProtoBuf.cpp',
	'execDetailsEndProtoBuf.cpp',
	'execDetailsProtoBuf.cpp',
	'familyCodesProtoBuf.cpp',
	'fundamentalsDataProtoBuf.cpp',
	'headTimestampProtoBuf.cpp',
	'histogramDataProtoBuf.cpp',
	'historicalDataEndProtoBuf.cpp',
	'historicalDataProtoBuf.cpp',
	'historicalDataUpdateProtoBuf.cpp',
	'historicalNewsEndProtoBuf.cpp',
	'historicalNewsProtoBuf.cpp',
	'historicalScheduleProtoBuf.cpp',
	'historicalTicksBidAskProtoBuf.cpp',
	'historicalTicksLastProtoBuf.cpp',
	'historicalTicksProtoBuf.cpp',
	'managedAccountsProtoBuf.cpp',
	'marketDataTypeProtoBuf.cpp',
	'marketDepthExchangesProtoBuf.cpp',
	'marketRuleProtoBuf.cpp',
	'newsArticleProtoBuf.cpp',
	'newsProvidersProtoBuf.cpp',
	'nextValidIdProtoBuf.cpp',
	'openOrderProtoBuf.cpp',
	'openOrdersEndProtoBuf.cpp',
	'orderBoundProtoBuf.cpp',
	'orderStatusProtoBuf.cpp',
	'pnlProtoBuf.cpp',
	'pnlSingleProtoBuf.cpp',
	'positionEndProtoBuf.cpp',
	'positionMultiEndProtoBuf.cpp',
	'positionMultiProtoBuf.cpp',
	'positionProtoBuf.cpp',
	'realTimeBarTickProtoBuf.cpp',
	'receiveFAProtoBuf.cpp',
	'replaceFAEndProtoBuf.cpp',
	'rerouteMarketDataRequestProtoBuf.cpp',
	'rerouteMarketDepthRequestProtoBuf.cpp',
	'scannerDataProtoBuf.cpp',
	'scannerParametersProtoBuf.cpp',
	'secDefOptParameterEndProtoBuf.cpp',
	'secDefOptParameterProtoBuf.cpp',
	'smartComponentsProtoBuf.cpp',
	'softDollarTiersProtoBuf.cpp',
	'symbolSamplesProtoBuf.cpp',
	'tickByTickDataProtoBuf.cpp',
	'tickGenericProtoBuf.cpp',
	'tickNewsProtoBuf.cpp',
	'tickOptionComputationProtoBuf.cpp',
	'tickPriceProtoBuf.cpp',
	'tickReqParamsProtoBuf.cpp',
	'tickSizeProtoBuf.cpp',
	'tickSnapshotEndProtoBuf.cpp',
	'tickStringProtoBuf.cpp',
	'updateAccountTimeProtoBuf.cpp',
	'updateAccountValueProtoBuf.cpp',
	'updateConfigResponseProtoBuf.cpp',
	'updateMarketDepthL2ProtoBuf.cpp',
	'updateMarketDepthProtoBuf.cpp',
	'updateNewsBulletinProtoBuf.cpp',
	'updatePortfolioProtoBuf.cpp',
	'userInfoProtoBuf.cpp',
	'verifyCompletedProtoBuf.cpp',
	'verifyMessageApiProtoBuf.cpp',
	'wshEventDataProtoBuf.cpp',
	'wshMetaDataProtoBuf.cpp'
)

# **************************************
# *** Constrol Addition Source Files ***
# **************************************

if system != 'windows'

source_files_twsclient += source_files_twsclient_protobuf

endif