# *******************************
# *** Autor: Reymon Dev       ***
# *** Datum: 08. Juli. 2026   ***
# *** Aktua: 08. Juli. 2026   ***
# *** Lizenz: AGPL-3-or-later ***
# *******************************

source_files_twsclient_orders = files(
	'completedOrder.cpp',
	'completedOrdersEnd.cpp',
	'openOrder.cpp',
	'openOrderEnd.cpp',
	'orderOperations.cpp',
	'orderStatus.cpp'
)

# **************************************
# *** Constrol Addition Source Files ***
# **************************************

source_files_twsclient += source_files_twsclient_orders