# *****************************
# *** Autor: Reymon Dev     ***
# *** Datum: 26. Juli. 2026 ***
# *** Aktua: 27. Juli. 2026 ***
# *** Lizenz: MIT           ***
# *****************************

SOURCE_FILES_TWSCLIENT_ORDERS = files(
	'bracketSample.cpp',
	'completedOrder.cpp',
	'completedOrdersEnd.cpp',
	'conditionSamples.cpp',
	'hedgeSample.cpp',
	'ibkratsSample.cpp',
	'ocaSamples.cpp',
	'openOrder.cpp',
	'openOrderEnd.cpp',
	'orderOperations.cpp',
	'orderStatus.cpp',
	'submitStockBuyLimit.cpp',
	'whatIfSamples.cpp'
)